/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package round_button;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import round_button.code.Etudiant;
import round_button.code.Filier;
import round_button.code.traitementFichier;

/**
 *
 * @author acer
 */
public class Ajouter extends javax.swing.JFrame {

    /**
     * Creates new form Ajouter
     */
    public Ajouter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        cne = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        prenom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        nom = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        choix = new javax.swing.JComboBox<>();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        f = new javax.swing.JRadioButton();
        m = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        enregister = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 24)); // NOI18N
        jLabel6.setText("CNE:");
        jLabel6.setMaximumSize(new java.awt.Dimension(30, 20));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(260, 100, 100, 30);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(250, 130, 80, 2);
        getContentPane().add(cne);
        cne.setBounds(340, 110, 240, 30);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 24)); // NOI18N
        jLabel2.setText("Nom:");
        jLabel2.setMaximumSize(new java.awt.Dimension(30, 20));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 150, 100, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(250, 180, 80, 2);
        getContentPane().add(prenom);
        prenom.setBounds(340, 190, 240, 30);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 24)); // NOI18N
        jLabel3.setText("Prenom:");
        jLabel3.setMaximumSize(new java.awt.Dimension(30, 20));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 190, 100, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(240, 220, 90, 10);
        getContentPane().add(nom);
        nom.setBounds(340, 150, 240, 30);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(240, 260, 160, 20);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 24)); // NOI18N
        jLabel4.setText("DateNaissance:");
        jLabel4.setMaximumSize(new java.awt.Dimension(30, 20));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 230, 190, 30);
        getContentPane().add(date);
        date.setBounds(340, 270, 230, 30);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(230, 320, 100, 30);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 24)); // NOI18N
        jLabel5.setText("Filier :");
        jLabel5.setMaximumSize(new java.awt.Dimension(30, 20));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 290, 190, 40);

        choix.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        choix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wisd", "BigData", "Msid", "Mql", "Midvi" }));
        choix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixActionPerformed(evt);
            }
        });
        getContentPane().add(choix);
        choix.setBounds(340, 310, 170, 23);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(230, 360, 100, 30);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 24)); // NOI18N
        jLabel7.setText("Sexe:");
        jLabel7.setMaximumSize(new java.awt.Dimension(30, 20));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 330, 190, 40);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(230, 320, 100, 30);

        f.setText("Female");
        f.setBorder(null);
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });
        getContentPane().add(f);
        f.setBounds(350, 360, 130, 15);

        m.setText("Male");
        m.setBorder(null);
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });
        getContentPane().add(m);
        m.setBounds(350, 380, 130, 20);

        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 400, 130, 50);

        enregister.setText("Enregistrer");
        enregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregisterActionPerformed(evt);
            }
        });
        getContentPane().add(enregister);
        enregister.setBounds(590, 320, 150, 50);

        jButton3.setText("Annuler");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(590, 380, 150, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Desktop\\ajouter2.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -180, 1290, 1000);

        getAccessibleContext().setAccessibleName("ajouter");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        roundButton roundButton = new roundButton();
        roundButton.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        cne.setText("");
        nom.setText("");
        prenom.setText("");
        date.setDate(null);
                
                
               
    }//GEN-LAST:event_jButton3ActionPerformed

    private void choixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_choixActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_mActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_fActionPerformed
     ArrayList<Etudiant> E;
     traitementFichier tf;
     Filier filiere;
    private void enregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregisterActionPerformed
       String filier=choix.getSelectedItem().toString();
       String s1,s2,s3,s4,s5,s6;
       s1=cne.getText();
       s2=nom.getText();
       s3=prenom.getText();
       Date s=date.getDate();
       SimpleDateFormat formatt=new SimpleDateFormat("dd/MM/yyyy");
       String datefinal=formatt.format(s);
       String sexe;
       if(f.isSelected()){
           sexe=f.getText();
           
       }
       else{
           sexe=m.getText();
       }
       if(filier.equals("Wisd")){
           try {
               tf=new traitementFichier("Wisd.txt");
               filiere=new Filier("Wisd",1);
               E=new ArrayList<Etudiant>();
               E=tf.Lecture(E);
               Etudiant e=new Etudiant(s1,s2,s3,datefinal,filiere,sexe);
               tf.addToFile(e, E);
               
           } catch (IOException ex) {
               Logger.getLogger(Ajouter.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
       if(filier.equals("BigData")){
           try {
               tf=new traitementFichier("BigData.txt");
               filiere=new Filier("BigData",2);
               E=new ArrayList<Etudiant>();
               E=tf.Lecture(E);
               Etudiant e=new Etudiant(s1,s2,s3,datefinal,filiere,sexe);
               tf.addToFile(e, E);
               
           } catch (IOException ex) {
               Logger.getLogger(Ajouter.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
       if(filier.equals("Msid")){
           try {
               tf=new traitementFichier("Msid.txt");
               filiere=new Filier("Msid",3);
                E=new ArrayList<Etudiant>();
               E=tf.Lecture(E);
               Etudiant e=new Etudiant(s1,s2,s3,datefinal,filiere,sexe);
               tf.addToFile(e, E);
               
           } catch (IOException ex) {
               Logger.getLogger(Ajouter.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
       if(filier.equals("Mql")){
           try {
               tf=new traitementFichier("Mql.txt");
               filiere=new Filier("Mql",4);
                E=new ArrayList<Etudiant>();
               E=tf.Lecture(E);
               Etudiant e=new Etudiant(s1,s2,s3,datefinal,filiere,sexe);
               tf.addToFile(e, E);
               
           } catch (IOException ex) {
               Logger.getLogger(Ajouter.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
       if(filier.equals("Midvi")){
            try {
               tf=new traitementFichier("Midvi.txt");
               filiere=new Filier("Midvi",5);
                E=new ArrayList<Etudiant>();
               E=tf.Lecture(E);
               Etudiant e=new Etudiant(s1,s2,s3,datefinal,filiere,sexe);
               tf.addToFile(e, E);
               
           } catch (IOException ex) {
               Logger.getLogger(Ajouter.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    }//GEN-LAST:event_enregisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajouter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> choix;
    private javax.swing.JTextField cne;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton enregister;
    private javax.swing.JRadioButton f;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JRadioButton m;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    // End of variables declaration//GEN-END:variables
}
