/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package round_button;

import java.awt.Color;
import java.awt.Component;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import round_button.code.Etudiant;
import round_button.code.traitementFichier;

/**
 *
 * @author acer
 */
public class Chercher extends javax.swing.JFrame {

    /**
     * Creates new form Chercher
     */
    public Chercher() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rech = new javax.swing.JButton();
        txt = new javax.swing.JTextField();
        msid = new javax.swing.JButton();
        wisd = new javax.swing.JButton();
        midvi = new javax.swing.JButton();
        bigdata = new javax.swing.JButton();
        mql = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        rech.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Desktop\\iconerecherche4.jpg")); // NOI18N
        rech.setText("jButton2");
        rech.setBorder(null);
        rech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechActionPerformed(evt);
            }
        });
        getContentPane().add(rech);
        rech.setBounds(330, 80, 50, 30);

        txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActionPerformed(evt);
            }
        });
        getContentPane().add(txt);
        txt.setBounds(370, 80, 220, 30);

        msid.setText("Msid");
        msid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msidActionPerformed(evt);
            }
        });
        getContentPane().add(msid);
        msid.setBounds(40, 190, 130, 30);

        wisd.setText("Wisd");
        wisd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wisdActionPerformed(evt);
            }
        });
        getContentPane().add(wisd);
        wisd.setBounds(40, 150, 130, 30);

        midvi.setText("Midvi");
        midvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midviActionPerformed(evt);
            }
        });
        getContentPane().add(midvi);
        midvi.setBounds(40, 270, 130, 30);

        bigdata.setText("BigData");
        bigdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigdataActionPerformed(evt);
            }
        });
        getContentPane().add(bigdata);
        bigdata.setBounds(40, 230, 130, 30);

        mql.setText("Mql");
        mql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mqlActionPerformed(evt);
            }
        });
        getContentPane().add(mql);
        mql.setBounds(40, 310, 130, 30);

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CNE", "Name", "LastName", "Date", "Filiere", "sexe"
            }
        ));
        tab.setSelectionBackground(new java.awt.Color(255, 0, 0));
        jScrollPane1.setViewportView(tab);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 120, 570, 320);

        jToggleButton1.setText("Menu");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(10, 390, 170, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Desktop\\rechercheStudent.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-130, -50, 1020, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public ArrayList<Etudiant> rechercher(ArrayList<Etudiant> E,String s,String rech){
          ArrayList<Etudiant> taBreturner=new ArrayList<Etudiant>();
          String nv;
          for(Etudiant e:E){
              nv="e.get"+rech+"()";
              if(nv.equals(s)){
                  taBreturner.add(e);
              }
          }
          return taBreturner;
    }
    DefaultTableModel dtm;
    traitementFichier tf;
    ArrayList<Etudiant> E;
    private void rechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechActionPerformed
        Object[] object=new Object[]{"CNE","name","lastname"};
        String s = (String) JOptionPane.showInputDialog(rech, 
        "Rechercher par ?",
        "Type de recherche",
        JOptionPane.QUESTION_MESSAGE, 
        null, 
        object, 
        object[0]);
        int x;
        String valrechercher=txt.getText();
        ArrayList<Object[]> resultat=new ArrayList<Object[]>();
        
        if(s.equals("CNE")){
            x=dtm.getRowCount();
           
           
             

        
            for(int i=0;i<x;i++){
                String check=(String) dtm.getValueAt(i, 0);
                
                if(check.equals(valrechercher)){
                    
                    resultat.add(new Object[]{dtm.getValueAt(i, 0),dtm.getValueAt(i, 1),dtm.getValueAt(i, 2),dtm.getValueAt(i, 3),dtm.getValueAt(i,4),dtm.getValueAt(i, 5)});
                      
                }
            }
            dtm.setNumRows(0);
            for(Object[] o:resultat ){
                dtm.addRow(o);
            }
            
        }
        if(s.equals("name")){
             x=dtm.getRowCount();
           
           
             

        
            for(int i=0;i<x;i++){
                String check=(String) dtm.getValueAt(i, 1);
                
                if(check.equals(valrechercher)){
                    
                    resultat.add(new Object[]{dtm.getValueAt(i, 0),dtm.getValueAt(i, 1),dtm.getValueAt(i, 2),dtm.getValueAt(i, 3),dtm.getValueAt(i,4),dtm.getValueAt(i, 5)});
                      
                }
            }
            dtm.setNumRows(0);
            for(Object[] o:resultat ){
                dtm.addRow(o);
            }
            
        }
        if(s.equals("lastname")){
             x=dtm.getRowCount();
           
           
             

        
            for(int i=0;i<x;i++){
                String check=(String) dtm.getValueAt(i, 2);
                
                if(check.equals(valrechercher)){
                    
                    resultat.add(new Object[]{dtm.getValueAt(i, 0),dtm.getValueAt(i, 1),dtm.getValueAt(i, 2),dtm.getValueAt(i, 3),dtm.getValueAt(i,4),dtm.getValueAt(i, 5)});
                      
                }
            }
            dtm.setNumRows(0);
            for(Object[] o:resultat ){
                dtm.addRow(o);
            }
            
        }
        
        
        
    }//GEN-LAST:event_rechActionPerformed

    private void txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActionPerformed

    private void mqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mqlActionPerformed
        dtm=(DefaultTableModel)tab.getModel();
       
        try {
                E=new ArrayList<Etudiant>();
                tf=new traitementFichier("Mql.txt");
                E=tf.Lecture(E);
                dtm.setNumRows(0);
                for(Etudiant e:E){
                    dtm.addRow(new Object[]{e.getCNE(),e.getName(),e.getLastname(),e.getDaten(),e.getFil(),e.getSexe()});
                }
            
            
        } catch (IOException ex) {
            Logger.getLogger(Chercher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mqlActionPerformed

    private void bigdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigdataActionPerformed
        dtm=(DefaultTableModel)tab.getModel();
       
        try {
                E=new ArrayList<Etudiant>();
                tf=new traitementFichier("BigData.txt");
                E=tf.Lecture(E);
                dtm.setNumRows(0);
                for(Etudiant e:E){
                    dtm.addRow(new Object[]{e.getCNE(),e.getName(),e.getLastname(),e.getDaten(),e.getFil(),e.getSexe()});
                }
            
            
        } catch (IOException ex) {
            Logger.getLogger(Chercher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bigdataActionPerformed
    
    private void wisdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wisdActionPerformed
        dtm=(DefaultTableModel)tab.getModel();
       
        try {
                E=new ArrayList<Etudiant>();
                tf=new traitementFichier("Wisd.txt");
                E=tf.Lecture(E);
                dtm.setNumRows(0);
                for(Etudiant e:E){
                    dtm.addRow(new Object[]{e.getCNE(),e.getName(),e.getLastname(),e.getDaten(),e.getFil(),e.getSexe()});
                }
           
            
        } catch (IOException ex) {
            Logger.getLogger(Chercher.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_wisdActionPerformed

    private void midviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midviActionPerformed
        dtm=(DefaultTableModel)tab.getModel();
       
        try {
                E=new ArrayList<Etudiant>();
                tf=new traitementFichier("Midvi.txt");
                E=tf.Lecture(E);
                dtm.setNumRows(0);
                for(Etudiant e:E){
                    dtm.addRow(new Object[]{e.getCNE(),e.getName(),e.getLastname(),e.getDaten(),e.getFil(),e.getSexe()});
                }
           
            
        } catch (IOException ex) {
            Logger.getLogger(Chercher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_midviActionPerformed

    private void msidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msidActionPerformed
        dtm=(DefaultTableModel)tab.getModel();
       
        try {
                E=new ArrayList<Etudiant>();
                tf=new traitementFichier("Msid.txt");
                E=tf.Lecture(E);
                dtm.setNumRows(0);
                for(Etudiant e:E){
                    dtm.addRow(new Object[]{e.getCNE(),e.getName(),e.getLastname(),e.getDaten(),e.getFil(),e.getSexe()});
                }
           
            
        } catch (IOException ex) {
            Logger.getLogger(Chercher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_msidActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        roundButton rd=new roundButton();
        rd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chercher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chercher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chercher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chercher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chercher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bigdata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton midvi;
    private javax.swing.JButton mql;
    private javax.swing.JButton msid;
    private javax.swing.JButton rech;
    private javax.swing.JTable tab;
    private javax.swing.JTextField txt;
    private javax.swing.JButton wisd;
    // End of variables declaration//GEN-END:variables
}
